version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - /opt/mysql-test-olc-systems:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080